import { gamesPlayed } from './ranking'
function shuffle(list){return[...list].sort(()=>Math.random()-.5)}
function pairKey(a,b){return[a,b].sort().join('|')}
function strength(p){return Number(p.strength||1)+Number(p.form||0)}
function history(matches){const together=new Map(),against=new Map();for(const m of matches){const a=m.team_a||[],b=m.team_b||[];for(const team of[a,b])for(let i=0;i<team.length;i++)for(let j=i+1;j<team.length;j++){const k=pairKey(team[i],team[j]);together.set(k,(together.get(k)||0)+1)}for(const x of a)for(const y of b){const k=pairKey(x,y);against.set(k,(against.get(k)||0)+1)}}return{together,against}}
function teamSum(team){return team.reduce((s,p)=>s+strength(p),0)}
function teamPenalty(team,h){let p=0;for(let i=0;i<team.length;i++)for(let j=i+1;j<team.length;j++)p+=h.together.get(pairKey(team[i].id,team[j].id))||0;return p}
function opponentPenalty(a,b,h){let p=0;for(const x of a)for(const y of b)p+=h.against.get(pairKey(x.id,y.id))||0;return p}
export function createNextMatch(players,matches,mode){const[sizeA,sizeB]=String(mode).split('v').map(Number),needed=sizeA+sizeB,active=players.filter(p=>p.active!==false);if(!sizeA||!sizeB)throw new Error('Ungültiger Spielmodus.');if(active.length<needed)throw new Error(`Für ${mode} brauchst du ${needed} aktive Spieler. Aktuell: ${active.length}.`);const pool=shuffle(active).sort((a,b)=>gamesPlayed(a.id,matches)-gamesPlayed(b.id,matches)||strength(b)-strength(a)).slice(0,needed),h=history(matches);let best=null;for(let i=0;i<2500;i++){const c=shuffle(pool),teamA=c.slice(0,sizeA),teamB=c.slice(sizeA,needed),gameCounts=[...teamA,...teamB].map(p=>gamesPlayed(p.id,matches));const score=Math.abs(teamSum(teamA)-teamSum(teamB))*100+(Math.max(...gameCounts)-Math.min(...gameCounts))*80+(teamPenalty(teamA,h)+teamPenalty(teamB,h))*30+opponentPenalty(teamA,teamB,h)*8+Math.random();if(!best||score<best.score)best={teamA,teamB,score}}return{mode,team_a:best.teamA.map(p=>p.id),team_b:best.teamB.map(p=>p.id),score_a:null,score_b:null}}
export function calculateForm(players,matches){const form=Object.fromEntries(players.map(p=>[p.id,0]));for(const m of matches){if(m.score_a===null||m.score_b===null||m.score_a===''||m.score_b==='')continue;const a=Number(m.score_a),b=Number(m.score_b);if(a===b)continue;const winners=a>b?m.team_a:m.team_b,losers=a>b?m.team_b:m.team_a;for(const id of winners||[])form[id]=Number(((form[id]||0)+.01).toFixed(2));for(const id of losers||[])form[id]=Number(((form[id]||0)-.01).toFixed(2))}return form}
